openapi: 3.0.3
info:
  title: Wallet API
  description: API электронного кошелька
  version: 1.0.0
servers:
- url: https://api.wallet.example.com
paths:
  /v1/wallets/{walletId}/cards:
    get:
      tags:
      - Card
      summary: Получить карты в выбранном кошельке
      operationId: getCardsApplications
      parameters:
      - name: walletId
        in: path
        description: Идентификатор кошелька
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Successful request with cards and applications
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardsAndApplicationResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: TOKEN_INVALID
                message: Authorization token invalid
                traceId: 550e8400-e29b-41d4-a716-446655440000
        "404":
          description: Wallet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: WALLET_NOT_FOUND
                message: Wallet not found
                traceId: 550e8400-e29b-41d4-a716-446655440000
      security:
      - bearerAuth: []
    post:
      tags:
      - Card
      summary: Создать виртуальную карту
      operationId: createVirtualCard
      parameters:
      - name: Idempotency-Key
        in: header
        required: true
        schema: 
          type: string
          format: uuid
      - name: walletId
        in: path
        description: Идентификатор кошелька
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "202":
          description: Card creation request accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: TOKEN_INVALID
                message: Authorization token invalid
                traceId: 550e8400-e29b-41d4-a716-446655440000
        "404":
          description: Wallet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: WALLET_NOT_FOUND
                message: Wallet not found
                traceId: 550e8400-e29b-41d4-a716-446655440000
      security:
      - bearerAuth: []
components:
  schemas:
    CardsAndApplicationResponse:
      required:
      - cardApplications
      - cards
      type: object
      properties:
        cards:
          type: array
          items:
            $ref: "#/components/schemas/CardsAndApplicationResponse_cards"
        cardApplications:
          type: array
          items:
            $ref: "#/components/schemas/CardsAndApplicationResponse_cardApplications"
    CreateCardResponse:
      required:
      - cardApplicationId
      - status
      type: object
      properties:
        cardApplicationId:
          type: string
          format: uuid
        status:
          type: string
          enum:
          - PENDING
    ErrorResponse:
      required:
      - code
      - message
      - traceId
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        traceId:
          type: string
          format: uuid
    CardsAndApplicationResponse_cards:
      required:
      - cardId
      - cardNumber
      - status
      type: object
      properties:
        cardId:
          type: string
          format: uuid
        markedCardNumber:
          type: string
          example: '**** **** **** 1234'
        status:
          type: string
          enum:
          - ACTIVE
          - BLOCKED
          - CLOSED
    CardsAndApplicationResponse_cardApplications:
      required:
      - cardApplicationId
      - status
      type: object
      properties:
        cardApplicationId:
          type: string
          format: uuid
        status:
          type: string
          enum:
          - PENDING
          - COMPLETED
          - FAILED
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
